version: '3.8'

services:
  backend:
    build: ./backend
    container_name: boxletter-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/users.json:/app/users.json
      - ./backend/movies.json:/app/movies.json
    networks:
      - boxletter-network

  frontend:
    build: .
    container_name: boxletter-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - boxletter-network

networks:
  boxletter-network:
    driver: bridge